### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by hadiljr** [lgomesroc/Order#2]
Senti falta de testes unitários no projeto.
Seria importante pensar em faze-los, já que irá guiar muito do que será feito no projeto.

**Comment by lgomesroc** [comment]
hadiljr, você está correto. eu quero mostrar esse projeto para empresas e entrevistas. Pode ser que falte isso mesmo. Muito obrigado pela abertura da issues e vou fazer. Antes tenho que popular o banco de dados e também vou fazer isso. Valeu meu caro.
